### ISSUE TITLE
The code in gulpfile.js on github is different from the sample code in the Learning Susy book

### ISSUE THREAD

**Issue by yellowfish1220** [zellwk/gulp-susy-starter#2]
I find in page 25, your sample code is different from the source code on github:
https://github.com/zellwk/gulp-susy-starter/blob/master/gulpfile.js

Maybe there are some typos :D
![Image of gulpfile.js](https://github.com/yellowfish1220/images/blob/master/000.png)

**Comment by zellwk** [comment]
Hey man,

I can't find your image? :/

<br  
Stay awesome!

Zell
