### ISSUE TITLE
Long error

### ISSUE THREAD

**Issue by Kietil** [zellwk/gulp-susy-starter#3]
I think i should read the instructions given in the url.. but il just post the error in case you can teach me something^^

Maybe this is connected to Ruby etc; but here is the msg i got after npm install

`npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated pangyp@2.3.3: use node-gyp@3+ instead
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global pangyp@2.3.3 should be installed with -g

> node-sass@2.1.1 install c:\Users\Kjetil\code\htmlcss\gulp-susy-starter\node_modules\node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/win32-x64-node-6.2/binding.node

> node-sass@2.1.1 postinstall c:\Users\Kjetil\code\htmlcss\gulp-susy-starter\node_modules\node-sass
> node scripts/build.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'c:\Users\Kjetil\code\htmlcss\gulp-susy-starter\node_modules\node-sass\node_modules\pangyp\bin\node-gyp'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
 Build failed`

**And with bower install i got this:** 
`npm WARN gulp-susy-starter@1.0.0 No repository field.
bower not-cached    https://github.com/ericam/susy.git#~2.2.2
bower resolve       https://github.com/ericam/susy.git#~2.2.2
bower not-cached    https://github.com/Team-Sass/breakpoint.git#~2.5.0
bower resolve       https://github.com/Team-Sass/breakpoint.git#~2.5.0
bower checkout      breakpoint-sass#v2.5.0
bower checkout      susy#2.2.12
bower mismatch      Version declared in the json (2.4.2) is different than the resolved one (2.5.0)
bower resolved      https://github.com/Team-Sass/breakpoint.git#2.5.0
bower not-cached    https://github.com/Team-Sass/Sassy-Maps.git#<1.0.0
bower resolve       https://github.com/Team-Sass/Sassy-Maps.git#<1.0.0
bower resolved      https://github.com/ericam/susy.git#2.2.12
bower checkout      sassy-maps#v0.4.0
bower resolved      https://github.com/Team-Sass/Sassy-Maps.git#0.4.0
bower install       breakpoint-sass#2.5.0
bower install       susy#2.2.12
bower install       sassy-maps#0.4.0

breakpoint-sass#2.5.0 bower_components\breakpoint-sass
└── sassy-maps#0.4.0

susy#2.2.12 bower_components\susy

sassy-maps#0.4.0 bower_components\sassy-maps

Kjetil@KJETIL ~/code/htmlcss/gulp-susy-starter (master)
$ gulp
(node:7232) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
C:\Users\Kjetil\code\htmlcss\gulp-susy-starter\node_modules\node-sass\lib\index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
    ^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (C:\Users\Kjetil\code\htmlcss\gulp-susy-starter\node_modules\node-sass\lib\index.js:22:11)
    at Object.<anonymous> (C:\Users\Kjetil\code\htmlcss\gulp-susy-starter\node_modules\node-sass\lib\index.js:188:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Kjetil\code\htmlcss\gulp-susy-starter\node_modules\gulp-sass\index.js:3:17)`

So.. what does all this mean exactly? I thought this would kickstart me into learning some gulp+susy etc.. but im clueless to the cmd message :)

**Comment by briansteeleca** [comment]
Just a thought... it may be your version of node.js. You may want to try an older version of node — check out this node version manager: https://github.com/tj/n

**Comment by zellwk** [comment]
It's because Node got updated, and the dependences were way too old. Fixed.
